### PR TITLE
Modernize packaging: replace versioneer with pyproject.toml

### LINKED ISSUE #4: Fails to install
```
pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines of the build output:
  File "/tmp/pdm-build-ni5_zw9o/versioneer.py", line 1480, in get_version
    return get_versions()["version"]
           ^^^^^^^^^^^^^^
  File "/tmp/pdm-build-ni5_zw9o/versioneer.py", line 1412, in get_versions
    cfg = get_config_from_root(root)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pdm-build-ni5_zw9o/versioneer.py", line 342, in get_config_from_root
    parser = configparser.SafeConfigParser()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
```

### PR DESCRIPTION
**Pull request by jdidion**
**Note:** This MR was largely generated by Claude and has not been completely reviewed by me (the human). You should feel free to defer your review until this warning has been removed.

## Summary
- Remove versioneer.py which uses `configparser.SafeConfigParser()` removed in Python 3.12
- Replace setup.py/setup.cfg with pyproject.toml (PEP 621)
- Use `importlib.metadata` for version detection
- Bump version to 0.2.1
- Fixes #4 (fails to install)

## Test plan
- [ ] Verify `pip install -e .` works on Python 3.10+
- [ ] Verify `pip install pokrok` works once published to PyPI
- [ ] Verify xphyle CI passes once this is released

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by jdidion** [comment]
Updated this branch (commit `c949f42`) to complete the modernization and add a test suite from scratch.

**Summary:** switched to setuptools-scm dynamic versioning (resolves #4, where the leftover versioneer reference broke installs on Python 3.12+), requires-python >=3.10, uv-managed dev group + ruff/pytest/coverage config, uv-based Makefile and CI.

**New test suite:** 132 tests covering the core API, styles, plugin base classes, and all four plugins (tqdm, progressbar2, halo, logging) against their real backends, at 98% coverage. The tests surfaced and fixed four real pre-existing bugs:
1. The logging plugin never loaded (passed `"Logging"` as the import name, so the stdlib logging module was never found).
2. `LoggingProgressMeter` passed a level-name string to `Logger.log()`, which requires an int.
3. progressbar2's `create_widgets` crashed on the default `widgets=None` style.
4. `BaseProgressMeterFactory.iterate` is a generator, so its `return iterable` fallback yielded nothing (now `yield from`).

**Verified:** `uv build` produces sdist+wheel, `uv run pytest` passes 132/132, ruff clean. I re-ran the suite independently: 132 pass.

This should close #4 once merged. Release (tag + `uv publish`) is a separate step.

> **Note:** This work was largely generated by Claude and has not been completely reviewed by me (the human). Feel free to defer review until this warning is removed.
